# Generated by Django 3.1.5 on 2021-02-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineral',
            name='weight',
        ),
        migrations.AlterField(
            model_name='dumptruck',
            name='carrying',
            field=models.PositiveIntegerField(verbose_name='Максимальная грузоподъемность, т'),
        ),
        migrations.RemoveField(
            model_name='dumptruck',
            name='mineral',
        ),
        migrations.CreateModel(
            name='DumpTruckMineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='Масса руды, т')),
                ('dump_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_weight', to='career.dumptruck', verbose_name='Масса руды, т')),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_weight', to='career.mineral', verbose_name='Самосвал')),
            ],
            options={
                'verbose_name': 'масса руды',
                'verbose_name_plural': 'масса руды',
            },
        ),
        migrations.AddField(
            model_name='dumptruck',
            name='mineral',
            field=models.ManyToManyField(related_name='dump_truck', through='career.DumpTruckMineral', to='career.Mineral', verbose_name='Руда в самосвале'),
        ),
    ]
