# Generated by Django 3.1.5 on 2021-02-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_auto_20210226_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumptruckmineral',
            name='mineral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_weight', to='career.mineral', verbose_name='Руда'),
        ),
    ]
