# Generated by Django 3.1.5 on 2021-02-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_auto_20210226_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumptruckmineral',
            name='dump_truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_weight_dumptruсk', to='career.dumptruck', verbose_name='Самосвал'),
        ),
        migrations.AlterField(
            model_name='dumptruckmineral',
            name='mineral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_weight_dumptruсk', to='career.mineral', verbose_name='Руда'),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='mineral',
        ),
        migrations.CreateModel(
            name='WarehouseMineral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='Масса руды, т')),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_weight_warehouse', to='career.mineral', verbose_name='Руда')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_weight_warehouse', to='career.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'масса руды',
                'verbose_name_plural': 'масса руды',
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='mineral',
            field=models.ManyToManyField(related_name='warehouse', through='career.WarehouseMineral', to='career.Mineral', verbose_name='Руда на складе'),
        ),
    ]
