# Generated by Django 3.1.5 on 2021-02-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_auto_20210226_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dumptruckmineral',
            options={'verbose_name': 'масса руды в самосвале', 'verbose_name_plural': 'масса руды в самосвалах'},
        ),
        migrations.AlterModelOptions(
            name='warehousemineral',
            options={'verbose_name': 'масса руды на складе', 'verbose_name_plural': 'масса руды на складах'},
        ),
    ]
