# Generated by Django 3.1.5 on 2021-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_auto_20210226_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumptruck',
            name='warehouse',
            field=models.ManyToManyField(related_name='dump_truck', to='career.Warehouse', verbose_name='Склад для разгрузки'),
        ),
    ]
