# Generated by Django 3.1.5 on 2021-02-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_dumptruck_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumptruck',
            name='mineral',
        ),
        migrations.AddField(
            model_name='dumptruck',
            name='mineral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dump_truck', to='career.mineral', verbose_name='Руда в самосвале'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='mineral',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='mineral',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='career.mineral', verbose_name='Руда на складе'),
            preserve_default=False,
        ),
    ]
