# Generated by Django 3.1.5 on 2021-02-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_auto_20210228_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumptruck',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='dumptruck',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dump_truck', to='career.warehouse', verbose_name='Склад для разгрузки'),
            preserve_default=False,
        ),
    ]
