# Generated by Django 3.1.5 on 2021-02-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_auto_20210228_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumptruck',
            name='mineral',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='mineral',
        ),
        migrations.AlterField(
            model_name='dumptruckmineral',
            name='dump_truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_dumptruсk', to='career.dumptruck', verbose_name='Самосвал'),
        ),
        migrations.AlterField(
            model_name='dumptruckmineral',
            name='mineral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_dumptruсk', to='career.mineral', verbose_name='Руда'),
        ),
        migrations.AlterField(
            model_name='warehousemineral',
            name='mineral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_warehouse', to='career.mineral', verbose_name='Руда'),
        ),
        migrations.AlterField(
            model_name='warehousemineral',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_warehouse', to='career.warehouse', verbose_name='Склад'),
        ),
    ]
