# Generated by Django 3.1.5 on 2021-02-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_dumptruck_coord_for_unloading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dumptruck',
            name='coord_for_unloading',
        ),
    ]
